esphome:
  name: power-meter
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  variant: ESP32C3
  framework:
    type: esp-idf

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  password: !secret ota_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Power-Meter Fallback Hotspot"
    password: !secret ap_key
    
uart:
  rx_pin: GPIO20
  tx_pin: GPIO21
  baud_rate: 9600
  
sensor:
  # Voltage
  - platform: template
    id: voltage
    name: "Voltage"
    accuracy_decimals: 0
    filters:
      - multiply: 0.1
    unit_of_measurement: "V"
    icon: "mdi:sine-wave"
    device_class: "Voltage"
    state_class: measurement
    
  # Current
  - platform: template
    id: current
    name: "Current"
    accuracy_decimals: 1
    filters:
      - multiply: 0.001
    unit_of_measurement: "A"
    icon: "mdi:current-ac"
    device_class: "current"
    state_class: measurement
    
  # active power
  - platform: template
    id: power
    name: "Power"
    accuracy_decimals: 0
    filters:
      - multiply: 1
    unit_of_measurement: "W"
    icon: "mdi:flash"
    device_class: "power"
    state_class: measurement

  #energy 
  - platform: "tuya"
    id: energy
    name: "Energy"
    sensor_datapoint: 1
    accuracy_decimals: 1
    filters:
      - multiply: 0.01
    unit_of_measurement: "kWh"
    icon: "mdi:sigma"
    device_class: "energy"
    state_class: measurement
    
switch:
  - platform: "tuya"
    id: "meter_power_relay"
    name: "Power Switch"
    switch_datapoint: 16
    icon: "mdi:power"
    on_turn_off:
      then:
        lambda: |-
          id(voltage).publish_state(0);
          id(current).publish_state(0);
          id(power).publish_state(0);

  - platform: "uart"
    id: sw_tuya_query_status
    data: [0x55, 0xaa, 0x00, 0x08, 0x00, 0x00, 0x07]
    name: "Update values"
    icon: mdi:reload

number:
  - platform: "tuya"
    name: "Over Voltage"
    number_datapoint: 101
    min_value: 250
    max_value: 300
    step: 1
    unit_of_measurement: "V"

  - platform: "tuya"
    name: "Under Voltage"
    number_datapoint: 102
    min_value: 150
    max_value: 190
    step: 1
    unit_of_measurement: "V"

  - platform: "tuya"
    name: "Current Limit"
    number_datapoint: 103
    min_value: 1
    max_value: 63
    step: 1
    unit_of_measurement: "A"

  - platform: "tuya"
    name: "Electric Leakage"
    number_datapoint: 104
    min_value: 10
    max_value: 100
    step: 1
    unit_of_measurement: "mA"
  
tuya:
  on_datapoint_update:
   - sensor_datapoint: 6
     datapoint_type: raw
     then:
      - lambda: |-
          id(voltage).publish_state((x[0] << 8 | x[1]));
          id(current).publish_state((x[3] << 8 | x[4]));
          id(power).publish_state((x[6] << 8 | x[7]));
